name: Docker Image CI

on:
  push:
  pull_request:

env:
  DOCKER_REGISTRY: "ghcr.io"
  DOCKER_REGISTRY_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  IMAGE_TAG: ${GITHUB_REF_NAME}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: True
      - name: Copy submodules into installed adons
        run: scripts/add_submodules_as_addons.sh
      - name: Login to Docker Registry
        run: echo -n "${{ secrets.DOCKER_REGISTRY_TOKEN }}" | docker login ${{ env.DOCKER_REGISTRY }} -u ${{ github.actor }} --password-stdin
      - name: Build and publish the Docker image
        run: |
          REGISTRY="${{ env.DOCKER_REGISTRY }}/marvinsoftwaresolutions" \
          TAG="${{ env.IMAGE_TAG }}" \
          docker buildx bake publish
