name: Docker Image CI

on:
  pull_request:

env:
  DOCKER_REGISTRY: "index.docker.io"
  DOCKER_REGISTRY_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      SHA_SHORT: ${{ steps.tag_id.outputs.sha_short }}
    steps:
      - id: checkout
        uses: actions/checkout@v4
        with:
          submodules: True
      - id: tag_id
        name: Get shirt SHA for image tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - id: install_submodules
        name: Copy submodules into installed adons
        run: scripts/add_submodules_as_addons.sh
      - id: test
        name: Build and publish the Docker image
        run: |
          REGISTRY="${{ env.DOCKER_REGISTRY }}/marvinsoftwaresolutions" \
          TAG="${{ steps.vars.outputs.sha_short }}" \
          docker buildx bake test
  # build:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - test
  #   steps:
  #     - id: checkout
  #       uses: actions/checkout@v4
  #       with:
  #         submodules: True
  #     - id: install_submodules
  #       name: Copy submodules into installed adons
  #       run: scripts/add_submodules_as_addons.sh
  #     - id: resgistry-login
  #       name: Login to Docker Registry
  #       run: echo -n "${{ env.DOCKER_REGISTRY_TOKEN }}" | docker login ${{ env.DOCKER_REGISTRY }} -u ${{ github.actor }} --password-stdin
  #     - id: build_and_push
  #       name: Build and publish the Docker image
  #       run: |
  #         REGISTRY="${{ env.DOCKER_REGISTRY }}/marvinsoftwaresolutions" \
  #         TAG="${{ env.IMAGE_TAG }}" \
  #         docker buildx bake test
